---
title: taCss
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: andras@andrastoth.eu
description: 'The most configurable CSS framework.

'
baseurl: "/tacss"
url: ''
github_username: ostux
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
